### ISSUE TITLE
As an admin I want to be able to create a new inventory for one product so the store can use it

### ISSUE THREAD

**Issue by zikky17** [KYH-Net23/InventoryProvider#1]
# Acceptance Criterias 

- [x]  There must be a create button that brings the admin to a form to create a new inventory.
- [x]  There must be a form for the admin to fill out “Inventory Name”, “Store Name”, “Location”.
- [x]  The form must be validated to guarantee correct information is written.
- [x]  If the information is validated, the information is saved to a database, and the admin is returned to the inventory page.
- [x]  The admin should see an error message if the inventory fails to be saved, and a success message if it succeeded. 
- [x]  If the form is invalid, the admin only needs to change the incorrect input field.

---

# Activity Diagram 

![Image](https://github.com/user-attachments/assets/62bda5f7-5152-49a6-b104-8231c5a74497)

---

# Sequence Diagram 

![Image](https://github.com/user-attachments/assets/a08d9928-7f90-4d4a-8f27-42d2b586dd80)

---

# TASKS

- [x] #7
   - [x] Create an inventory model that represents the input fields that are required. (“Inventory Name”, “Store Name”, “Location”, “etc”).
   - [x] Create classes and interfaces.
   - [x] Create an InventoryService class with an interface (InventoryService ).
   - [x] Create an InventoryRepository class with an interface (InventoryRepository).
   - [x] Create an InventoryFactory class.
   - [x] Create InventoryContext that implements DbContext

---

- [x] #13
   - [x] CreateNewInventory(Input formInput)
---

- [x] #15
   - [x] Add a “Create New Inventory” button in the Admin UI
   - [x] Add form when pressing the button, allowing admin to input in the fields. 
   - [x] Return error / success messages, if the Create was successful or not.
   - [x] Add a red border on the incorrect input fields.

---

- [x] #20
   - [x] Make sure the admin can't make any mistakes in the form. 
   - [x] Display an error message on missing / wrong input.

---

- [x] #23
   - [x] Make sure the InventoryRepository has an established connection to the correct database.

---

- [x] #25
   - [x] Write unit tests to ensure functionality is working correctly, write integration tests to ensure it cooperates with other systems.

# Test Cases

- [x] Test case 1: Successfully added a new inventory
Prerequisites:
Person is logged in as Admin
Go to the admin dashboard. 
Steps:
Admin clicks the Add new inventory button.
Admin fills out the form correctly.
Press Save.
Expected result:
New inventory is created, and the list of inventory is updated with the created inventory, with a success message.

- [x] Test case 2: Failed to add a new inventory
Prerequisites:
Person is logged in as Admin
Go to the admin dashboard. 
Steps:
Admin clicks the Add new inventory button.
Admin fills out the form incorrectly.
Press Save.
Expected result:
Error message is displayed.
