### ISSUE TITLE
As an Admin, I want to be able to change the details  of an existing inventory item so that the correct information is displayed.

### ISSUE THREAD

**Issue by zikky17** [KYH-Net23/InventoryProvider#3]
# Acceptance Criterias 

- [ ] There must be an edit button that brings the admin to a form to edit the details of the existing inventory item.
- [ ]  The edit button should be placed in an admin view for the inventory item(each inventory has its own button).
- [ ]  The form must be validated to guarantee correct information is written.
- [ ] If the information is validated, the information is saved to a database, and the admin is returned to the inventory page, with the updated list.
- [ ]  The admin should see an error message if the inventory fails to be saved, and a success message if it succeeded. 
- [ ]  If the form is invalid, the admin only needs to change the incorrect input field.

---

# Activity Diagram 

![Image](https://github.com/user-attachments/assets/3c377a87-ddb5-4616-8cb8-a9d883ab1e87)

---

# Sequence Diagram

![Image](https://github.com/user-attachments/assets/396fdad5-6c73-40ae-9256-2e369683a656)

---

# TASKS

- [ ] #44
   - [ ] Create an Edit button for each inventory item.
- [ ] #46
   - [ ] Create the Update method according to the sequence diagram.
- [ ] #48
   - [ ] Add an update inventory button in admin view.
   - [ ] Form is already filled with current information from the database on opening.
- [ ] #51
   - [ ] Make sure the admin can't make any mistakes in the form. 
   - [ ] Display an error message on missing / wrong input. 
- [ ] #54
   - [ ] Write unit tests to ensure functionality is working correctly, write integration tests to ensure it cooperates with other systems. 

---

# Test Case Descriptions

- [ ] Test case 1: Successfully updated an inventory item
Prerequisites:
Person is logged in as Admin
Go to the admin dashboard. 
Steps:
Admin clicks the Edit button on one of the inventories.
Admin fills out the form correctly.
Press Save.
Expected result:
Current inventory is updated, and the list of inventories is updated with the inventory, with a success message.

- [ ] Test case 2: Failed to update one inventory
Prerequisites:
Person is logged in as Admin
Go to the admin dashboard. 
Steps:
Admin clicks the Edit button.
Admin fills out the form incorrectly.
Press Save.
Expected result:
Error message is displayed.
